version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend_2
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=gbstu1nj9qpFE74nXW-YibXzM33Je5lDxjWCdqs3HKI
    volumes:
      - ./backend_2/docks.db:/root/docks.db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
